{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"cleaned_DataFrame\",\"occupancy_leading_by_property\",\"occupancy_leading_by_property_type\",\"customer_loyalty_demographics\",\"customer_demographics_by_property\",\"customer_demographics_by_property_type\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.139.2054.0 (24.12)+334ca1c95b576cc53924655643b0d36f21caac55"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "es-ES",
    "cultures": [
      {
        "name": "es-ES",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "1d988d97-3465-47bc-8546-91ac2f062807",
        "fromColumn": "Ingreso",
        "fromTable": "cleaned_DataFrame",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_5b945379-8ef4-4681-aba9-cbf0c678564f"
      },
      {
        "name": "9887d4eb-be0c-482b-b7b5-b7dd87e2d30c",
        "fromColumn": "Salida",
        "fromTable": "cleaned_DataFrame",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_be2d9c53-ab6e-48ef-a01a-9c315ddd4076"
      },
      {
        "name": "32075653-e3ef-44f6-8e21-e3248dd3c062",
        "fromColumn": "Fecha de Reservación",
        "fromTable": "cleaned_DataFrame",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a38adb0d-78af-49f3-8743-38884f3d39f3"
      },
      {
        "name": "AutoDetected_8abe9613-5a36-4716-9455-4f2bd40c4d82",
        "fromColumn": "Propiedad",
        "fromTable": "cleaned_DataFrame",
        "toColumn": "Propiedad",
        "toTable": "customer_demographics_by_property"
      },
      {
        "name": "AutoDetected_050b483a-f1c0-4104-8cfc-a6314dd19787",
        "fromColumn": "Propiedad",
        "fromTable": "occupancy_leading_by_property",
        "toColumn": "Propiedad",
        "toTable": "customer_demographics_by_property"
      },
      {
        "name": "AutoDetected_8068db19-e956-4d34-84f9-a7755effd636",
        "fromColumn": "Property Type",
        "fromTable": "occupancy_leading_by_property_type",
        "toColumn": "Property Type",
        "toTable": "customer_demographics_by_property_type"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "cleaned_DataFrame",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Código de confirmación",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84d2d712-c1d0-4901-97fa-040b20e96fc8",
            "sourceColumn": "Código de confirmación",
            "summarizeBy": "none"
          },
          {
            "name": "Estado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "26c649fb-dbb3-43d1-abca-cc634cb02102",
            "sourceColumn": "Estado",
            "summarizeBy": "none"
          },
          {
            "name": "Nombre del huésped",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2eb4622b-d4dd-4657-b5df-f9e6f32294be",
            "sourceColumn": "Nombre del huésped",
            "summarizeBy": "none"
          },
          {
            "name": "Contacto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b96d688b-bab2-4ad9-8450-4dbc6d758412",
            "sourceColumn": "Contacto",
            "summarizeBy": "none"
          },
          {
            "name": "Número de adultos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6ee41d3c-76d2-49a0-adf1-2bc1254302fb",
            "sourceColumn": "Número de adultos",
            "summarizeBy": "sum"
          },
          {
            "name": "Número de niños",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e55c5020-343a-407d-ac3a-ccadf4b7e341",
            "sourceColumn": "Número de niños",
            "summarizeBy": "sum"
          },
          {
            "name": "Número de bebés",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1784cda1-1745-4b1f-822d-5f1fc8fe2832",
            "sourceColumn": "Número de bebés",
            "summarizeBy": "sum"
          },
          {
            "name": "Ingreso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c45d44b2-bc20-4016-8dcf-2ead17ef0eb1",
            "sourceColumn": "Ingreso",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variación",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_5b945379-8ef4-4681-aba9-cbf0c678564f"
                },
                "isDefault": true,
                "relationship": "1d988d97-3465-47bc-8546-91ac2f062807"
              }
            ]
          },
          {
            "name": "Salida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f4ba4400-9a99-42b6-8e57-2da23029f221",
            "sourceColumn": "Salida",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variación",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_be2d9c53-ab6e-48ef-a01a-9c315ddd4076"
                },
                "isDefault": true,
                "relationship": "9887d4eb-be0c-482b-b7b5-b7dd87e2d30c"
              }
            ]
          },
          {
            "name": "Número de noches",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1293533e-22ff-4897-91c8-526c5b8cf7d5",
            "sourceColumn": "Número de noches",
            "summarizeBy": "sum"
          },
          {
            "name": "Fecha de Reservación",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f4791c0d-643c-4a26-8d75-12e348a2e6f8",
            "sourceColumn": "Fecha de Reservación",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variación",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_a38adb0d-78af-49f3-8743-38884f3d39f3"
                },
                "isDefault": true,
                "relationship": "32075653-e3ef-44f6-8e21-e3248dd3c062"
              }
            ]
          },
          {
            "name": "Propiedad",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "317df47f-169c-4150-9d1c-8797520a623a",
            "sourceColumn": "Propiedad",
            "summarizeBy": "none"
          },
          {
            "name": "Ingresos Totales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "72922e33-148e-44a8-af50-ce2c4a8127af",
            "sourceColumn": "Ingresos Totales",
            "summarizeBy": "sum"
          },
          {
            "name": "Property Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1282f191-1086-49ef-a894-54eef13e192d",
            "sourceColumn": "Property Type",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "20cca5dd-c361-48e2-84ee-3bb784ca5680",
        "partitions": [
          {
            "name": "cleaned_DataFrame",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Csv.Document(File.Contents(\"C:\\Documents\\AirBNB\\github_repository\\cleaned_DataFrame.csv\"),[Delimiter=\",\", Columns=14, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"Código de confirmación\", type text}, {\"Estado\", type text}, {\"Nombre del huésped\", type text}, {\"Contacto\", type text}, {\"Número de adultos\", Int64.Type}, {\"Número de niños\", Int64.Type}, {\"Número de bebés\", Int64.Type}, {\"Ingreso\", type date}, {\"Salida\", type date}, {\"Número de noches\", Int64.Type}, {\"Fecha de Reservación\", type date}, {\"Propiedad\", type text}, {\"Ingresos Totales\", type number}, {\"Property Type\", type text}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_5598501c-f88f-4feb-ae58-4bfd63c1c3bd",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2bc3cf7a-9f1c-4157-93e6-4f5a9823ccea",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e0890924-b5ab-4cc1-9f2e-b3ad1954d013",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6b52d7cf-e119-412f-9268-bd15d370aa92",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ecfa78e6-0b7c-4f4b-bb96-9937d4ab4dab",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fdc45947-4d15-400a-980d-05ca04afe184",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [NroTrimestre]",
            "isHidden": true,
            "lineageTag": "ffa42375-ad39-4555-acdc-fa9ac20aea30",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4983421b-bc1c-4ebb-9760-6190e1b5fbc5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "c115440f-cf20-42ad-94a7-2ed0b5421d69",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "05f3c1f6-3049-4ea5-a866-dcd61cea201a",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "41624d39-e411-4ea7-80fb-e132c25cd57f",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "89fc04ec-0693-4a36-9cb4-53e7ecfdd071",
                "ordinal": 3
              }
            ],
            "lineageTag": "a1d54338-9b55-4817-bb5d-443e2e910226"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "66a44085-1f17-4c15-8f7d-8e2edf3b40dd",
        "partitions": [
          {
            "name": "DateTableTemplate_5598501c-f88f-4feb-ae58-4bfd63c1c3bd",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_5b945379-8ef4-4681-aba9-cbf0c678564f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "fb85ec53-98d8-4fa4-8fdb-39430aa17e92",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "27ec7644-00ad-49b7-a76e-da4bdc71d8b5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "56f69372-a2c1-4b88-a552-50700d55f799",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "9cd3d30c-ee80-47f5-bf17-ba3e0aa2eb5e",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b50c8951-e6fe-44af-bfac-2ae6d165e8f9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [NroTrimestre]",
            "isHidden": true,
            "lineageTag": "af2f3291-cacd-47d2-a7bd-1f9f66f5d697",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e8c2d48f-159e-46bb-84e2-08f107e630b0",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "7a9a4acd-30bd-430f-9cbb-33b03d6c65f4",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "4315f3c7-c71c-4086-849f-b36fedc7baaf",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "4aecf64e-28f8-4ef8-a7e8-4b1e6963e483",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "cfa2abe0-809b-4135-a522-15eda4c29024",
                "ordinal": 3
              }
            ],
            "lineageTag": "df0a5781-d716-4de7-8859-c44a5eaed318"
          }
        ],
        "isHidden": true,
        "lineageTag": "e1a2c345-81bb-4518-8f2c-b498be4f2fda",
        "partitions": [
          {
            "name": "LocalDateTable_5b945379-8ef4-4681-aba9-cbf0c678564f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('cleaned_DataFrame'[Ingreso])), 1, 1), Date(Year(MAX('cleaned_DataFrame'[Ingreso])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_be2d9c53-ab6e-48ef-a01a-9c315ddd4076",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "754cc118-1e21-4957-a796-ff72a9cb7a36",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4a600746-9226-433e-bdc9-11ee1ae7d24f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d562748a-ccfc-4655-a6d2-260adef46eb9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "182d09a7-b049-4cd2-b85a-26d9b1a5d356",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "97ae1087-cb7d-4b25-8b85-12e76d6e165b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [NroTrimestre]",
            "isHidden": true,
            "lineageTag": "3535d1fa-f2a3-4d71-a294-43fc0a0cf31c",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "17679eb7-ee94-4c65-ad35-386675283f19",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "02d3e8f2-921a-4616-8fa7-85282f039c42",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "3d89171b-bc41-49d2-b3e6-21b757976b86",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "8ca9fd78-0f8e-4763-837a-d3d4f6fbe94f",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "81571168-9ecb-4d64-86a9-31181caa4ac1",
                "ordinal": 3
              }
            ],
            "lineageTag": "598b8e10-3a1e-4a57-8335-562791aa9046"
          }
        ],
        "isHidden": true,
        "lineageTag": "d5adfb03-0a90-41bf-a557-a1e5b23e12d8",
        "partitions": [
          {
            "name": "LocalDateTable_be2d9c53-ab6e-48ef-a01a-9c315ddd4076",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('cleaned_DataFrame'[Salida])), 1, 1), Date(Year(MAX('cleaned_DataFrame'[Salida])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_a38adb0d-78af-49f3-8743-38884f3d39f3",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5a25f094-b968-4907-b8ba-1616969de025",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3ad71b35-96a8-4f7a-a640-6f3f42e2f6a1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "81059f6d-c40f-46fa-a7f1-869a38430a5b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "e473cff9-b678-4979-98ce-a5c6aa229b55",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4d0bc365-a33a-4aa2-99da-fe2197055b6b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [NroTrimestre]",
            "isHidden": true,
            "lineageTag": "3a180131-caea-4a8d-9bfb-acd3207805d5",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c6c37e2f-718c-4e1c-a78b-a55074dd4d4d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "e2957714-6a38-4546-b8bf-17a8668efe05",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "064d2daf-413c-4302-8c85-89239ad0b22f",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "6f41a43f-50dd-4e47-a8fa-68a6862124b9",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "3f2afb0d-34d1-4830-be94-dea3afeeb7fc",
                "ordinal": 3
              }
            ],
            "lineageTag": "74b57e5c-6bee-43cc-9cb1-1b05e9150f0b"
          }
        ],
        "isHidden": true,
        "lineageTag": "45af7ff9-f222-4eec-ae77-9e0f3a882f12",
        "partitions": [
          {
            "name": "LocalDateTable_a38adb0d-78af-49f3-8743-38884f3d39f3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('cleaned_DataFrame'[Fecha de Reservación])), 1, 1), Date(Year(MAX('cleaned_DataFrame'[Fecha de Reservación])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "occupancy_leading_by_property",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Propiedad",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2abfe1a-6131-47fd-bbd9-68ac1932aa7a",
            "sourceColumn": "Propiedad",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9d1137f0-4e3d-44ef-abdb-52d0b7d124b6",
            "sourceColumn": "Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4877f134-fe90-4dc8-a9aa-ea01571b266c",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Nights Booked per Property",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d7ae73ad-ebbf-4175-863f-b04b4a3c5bd5",
            "sourceColumn": "Total Nights Booked per Property",
            "summarizeBy": "sum"
          },
          {
            "name": "Avg Lead Time per Property",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fa02489c-1a82-485b-80b2-8325023d9562",
            "sourceColumn": "Avg Lead Time per Property",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Available Nights",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "20d1054f-19a4-4108-8454-f2fd644c68f1",
            "sourceColumn": "Total Available Nights",
            "summarizeBy": "sum"
          },
          {
            "name": "Occupancy Rate (%)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e0921942-cdb5-4b4f-a499-79a6a25d473d",
            "sourceColumn": "Occupancy Rate (%)",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "d55f8fa9-a738-4670-8fbb-cd0e346d34b1",
        "partitions": [
          {
            "name": "occupancy_leading_by_property",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Csv.Document(File.Contents(\"C:\\Documents\\AirBNB\\github_repository\\occupancy_leading_by_property.csv\"),[Delimiter=\",\", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"Propiedad\", type text}, {\"Month\", Int64.Type}, {\"Year\", Int64.Type}, {\"Total Nights Booked per Property\", Int64.Type}, {\"Avg Lead Time per Property\", type number}, {\"Total Available Nights\", Int64.Type}, {\"Occupancy Rate (%)\", type number}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "occupancy_leading_by_property_type",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Property Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51a2cad2-a510-424f-89ec-7ca09c562a0a",
            "sourceColumn": "Property Type",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cd5ece97-62d6-4e51-8701-607e59e8c4fc",
            "sourceColumn": "Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0cb64131-e534-4649-bd9c-07aedbd6a26a",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Nights Booked per Property Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "be23cb9c-a33b-41c7-ad42-75afdc53d87a",
            "sourceColumn": "Total Nights Booked per Property Type",
            "summarizeBy": "sum"
          },
          {
            "name": "Avg Lead Time per Property Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2bdb26e5-9973-488d-b773-62f6affdd273",
            "sourceColumn": "Avg Lead Time per Property Type",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Available Nights",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b5330e85-b3a3-472a-8ccd-25e9ead40bb3",
            "sourceColumn": "Total Available Nights",
            "summarizeBy": "sum"
          },
          {
            "name": "Occupancy Rate (%)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2e9653dc-de91-4af2-a6ac-17fa6c06c202",
            "sourceColumn": "Occupancy Rate (%)",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "576108ed-765c-48d6-acb1-5d11b468a077",
        "partitions": [
          {
            "name": "occupancy_leading_by_property_type",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Csv.Document(File.Contents(\"C:\\Documents\\AirBNB\\github_repository\\occupancy_leading_by_property_type.csv\"),[Delimiter=\",\", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"Property Type\", type text}, {\"Month\", Int64.Type}, {\"Year\", Int64.Type}, {\"Total Nights Booked per Property Type\", Int64.Type}, {\"Avg Lead Time per Property Type\", type number}, {\"Total Available Nights\", Int64.Type}, {\"Occupancy Rate (%)\", type number}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "customer_loyalty_demographics",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Guest Identifier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "377f49d9-b4c9-45f2-8794-8d19ab9f99d6",
            "sourceColumn": "Guest Identifier",
            "summarizeBy": "none"
          },
          {
            "name": "Total Bookings",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "352fd9d3-3171-4a4b-8afe-7b634717d4de",
            "sourceColumn": "Total Bookings",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "77ff43ef-d7e6-46a2-a8c9-5513eef9fe75",
        "partitions": [
          {
            "name": "customer_loyalty_demographics",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Csv.Document(File.Contents(\"C:\\Documents\\AirBNB\\github_repository\\customer_loyalty_demographics.csv\"),[Delimiter=\",\", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"Guest Identifier\", type text}, {\"Total Bookings\", Int64.Type}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "customer_demographics_by_property",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Propiedad",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57afaa15-9721-45ff-9a26-866f71faf696",
            "sourceColumn": "Propiedad",
            "summarizeBy": "none"
          },
          {
            "name": "Número de adultos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c491837a-d37d-464f-98a5-e06a215c05b6",
            "sourceColumn": "Número de adultos",
            "summarizeBy": "sum"
          },
          {
            "name": "Número de niños",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d92d2122-558b-4162-a46f-29b0dc61d765",
            "sourceColumn": "Número de niños",
            "summarizeBy": "sum"
          },
          {
            "name": "Número de bebés",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ed099c58-feba-48e5-bfb0-51f0716d1220",
            "sourceColumn": "Número de bebés",
            "summarizeBy": "sum"
          },
          {
            "name": "Código de confirmación",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "18211614-b01f-4ff4-a52d-6445d74da3dd",
            "sourceColumn": "Código de confirmación",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "364671f7-9f4d-4362-879c-5efe9e2e9f00",
        "partitions": [
          {
            "name": "customer_demographics_by_property",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Csv.Document(File.Contents(\"C:\\Documents\\AirBNB\\github_repository\\customer_demographics_by_property.csv\"),[Delimiter=\",\", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"Propiedad\", type text}, {\"Número de adultos\", Int64.Type}, {\"Número de niños\", Int64.Type}, {\"Número de bebés\", Int64.Type}, {\"Código de confirmación\", Int64.Type}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "customer_demographics_by_property_type",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Property Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b346bad-f082-476c-a753-c577673885a0",
            "sourceColumn": "Property Type",
            "summarizeBy": "none"
          },
          {
            "name": "Número de adultos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5c068193-df4b-4814-b4ea-8c317900a047",
            "sourceColumn": "Número de adultos",
            "summarizeBy": "none"
          },
          {
            "name": "Número de niños",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0f4ea979-b8c6-4323-802d-bcf45f358b5a",
            "sourceColumn": "Número de niños",
            "summarizeBy": "none"
          },
          {
            "name": "Número de bebés",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b5ae33ab-ea62-435e-bacc-0de578639570",
            "sourceColumn": "Número de bebés",
            "summarizeBy": "none"
          },
          {
            "name": "Código de confirmación",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "64b18ddf-a82d-482c-93ad-4292e60cc861",
            "sourceColumn": "Código de confirmación",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "db87b099-877d-47f0-b9bd-debab48e0e41",
        "partitions": [
          {
            "name": "customer_demographics_by_property_type",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Csv.Document(File.Contents(\"C:\\Documents\\AirBNB\\github_repository\\customer_demographics_by_property_type.csv\"),[Delimiter=\",\", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"Property Type\", type text}, {\"Número de adultos\", Int64.Type}, {\"Número de niños\", Int64.Type}, {\"Número de bebés\", Int64.Type}, {\"Código de confirmación\", Int64.Type}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}